version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: pritunldb
    network_mode: bridge
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  pritunl:
    image: screencom/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    network_mode: bridge
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
      - 1194:1194
      - 1194:1194/udp
      - 19031:19031
      - 19031:19031/udp
      - 19032:19032
      - 19032:19032/udp
    environment:
      - TZ=UTC

  web:
    image: screencom/ubuntu:18.04
    container_name: web
    hostname: web
    network_mode: bridge
    privileged: true
    ports:
      - "2201:22"
    volumes:
      - ./web-entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
